### ISSUE TITLE
Symfony: Global Autowiring override

### ISSUE THREAD

**Issue by weaverryan** [weaverryan/the-open-source-list#3]
You can map _which_ class/interface should map to _which_ service on a service-by-service basis (e.g. if I'm registering service _B_, I can say the classes/interfaces for which this service should be used.

But, if service _B_ is registered by a vendor... you're kinda screwed. Likely, the yml/xml config would need to be extended to allow something like this:

``` yml
services:
    # ...

autowiring:
    Foo\Bar\BazInterface: service_foo
    Foo\Acme\Wow: other_service_bar
```

We should also look at other autowiring libraries to make sure this is the only configurable thing that still needs to be supported.
